Repository hashicorp/dev-portal, pull requests merged in 2022-05, with the labels that each got.

#415 feat: warm cache for tutorial paths
  .env
  .github/workflows/cache.yml
  scripts/warm-dotio-cache.ts
Labels: Tutorials

#420 refactor: format sitemap data on server
  src/views/product-tutorials-view/components/sitemap/helpers.ts
  src/views/product-tutorials-view/components/sitemap/index.tsx
  src/views/product-tutorials-view/components/sitemap/types.ts
  src/views/product-tutorials-view/server.ts
Labels: Tutorials

#438 style: fix tutorial badge readtime
  src/components/tutorial-meta/components/badges/badges.module.css
  src/components/tutorial-meta/components/badges/components/badge/badge.module.css
  src/components/tutorial-meta/components/badges/index.tsx
Labels: Tutorials

#437 cleanup: collection meta styles
  src/components/icon-tile/icon-tile.module.css
  src/views/collection-view/components/collection-meta/index.tsx
Labels: Tutorials

#412 feat: tutorials opt in / opt out
  src/components/button/index.tsx
  src/components/button/types.ts
  src/components/dialog/dialog.module.css
  src/components/dialog/index.tsx
  src/components/dialog/types.ts
  src/components/opt-in-out/components/opt-out-form/index.tsx
  src/components/opt-in-out/components/opt-out-form/opt-out-form.module.css
  src/components/opt-in-out/components/opt-out-form/types.ts
  src/components/opt-in-out/helpers/get-learn-redirect-path.ts
  src/components/opt-in-out/index.tsx
  src/components/opt-in-out/types.ts
  src/layouts/sidebar-sidecar/index.tsx
  src/layouts/sidebar-sidecar/sidebar-sidecar-layout.module.css
  src/layouts/sidebar-sidecar/types.ts
  src/pages/_middleware.ts
  src/views/collection-view/index.tsx
  src/views/product-tutorials-view/index.tsx
  src/views/tutorial-view/index.tsx
Labels: Tutorials

#455 chore: use product name for search placeholder
  src/views/docs-view/components/product-docs-search/index.tsx
Labels: chore

#459 Update Waypoint landing page content
  src/data/waypoint-landing.json
Labels: documentation

#496 feat: opt out form submits
  src/components/opt-in-out/components/opt-out-form/index.tsx
  src/components/opt-in-out/components/opt-out-form/types.ts
  src/components/opt-in-out/helpers/get-learn-redirect-path.ts
  src/components/opt-in-out/helpers/index.ts
  src/components/opt-in-out/helpers/make-beta-welcome-toast.tsx
  src/components/opt-in-out/helpers/platform-options.ts
  src/components/opt-in-out/helpers/post-form-data.ts
  src/components/opt-in-out/index.tsx
  src/hooks/use-opt-in-analytics-tracking.ts
  src/lib/analytics.ts
  src/pages/api/opt-out-feedback.ts
Labels: Tutorials
