Repository hashicorp/dev-portal, pull requests merged in 2022-06, with the labels that each got.

#469 fix: update tutorials anchor styles
  src/components/docs-anchor/index.tsx
  src/components/inline-link/docs.mdx
  src/components/inline-link/index.tsx
  src/components/inline-link/types.ts
  src/layouts/sidebar-sidecar/index.tsx
  src/views/error-views/dev-dot-versioned-404/index.tsx
  src/views/product-downloads-view/components/downloads-section/index.tsx
  src/views/tutorial-view/utils/mdx-components.tsx
Labels: Tutorials

#456 refactor: memoize collection api calls
  src/views/collection-view/server.ts
  src/views/tutorial-view/server.ts
  src/views/tutorial-view/utils/get-collection-context.ts
Labels: Tutorials

#505 Update Waypoint sidecar links on Install page
  src/data/waypoint-install.json
Labels: documentation

#549 chore: fix casing
  src/views/product-tutorials-view/helpers/heading-helpers.ts
Labels: Tutorials

#547 Update Vault docs landing page content
  src/pages/vault/docs/content.json
Labels: documentation

#577 Update homepage content
  src/views/homepage/components/hero/hero-with-video.tsx
  src/views/homepage/components/learn-section/index.tsx
  src/views/homepage/components/merchandising-slots/slots/vault-slot/index.tsx
  src/views/homepage/index.tsx
Labels: documentation

#504 Rephrase redundant section title
  src/data/waypoint-landing.json
Labels: documentation

#595 Add tutorials link to Vault sidecar
  src/data/vault-install.json
Labels: documentation

#624 Refine destinations for Resources
  src/components/sidebar/helpers/generate-resources-nav-items.ts
Labels: documentation

#647 [Do not merge] [HashiConf EU] Configure alert banners for day 1
  src/data/boundary.json
  src/data/consul.json
  src/data/nomad.json
  src/data/packer.json
  src/data/sentinel.json
  src/data/vagrant.json
  src/data/vault.json
  src/data/waypoint.json
Labels: do not merge

#651 Update alert banners for day 2
  src/data/boundary.json
  src/data/consul.json
Labels: do not merge
