Repository hashicorp/dev-portal, pull requests merged in 2023-06, with the labels that each got.

#1989 repo sync
  .github/workflows/repo-sync.yml
Labels: automated-reposync-pr

#1996 Add recertification copy to cert pages
  src/content/certifications/exam-faqs/consul-associate-002.mdx
  src/content/certifications/exam-faqs/terraform-associate-003.mdx
  src/content/certifications/exam-faqs/vault-associate-002.mdx
  src/content/certifications/exam-faqs/vault-operations-professional.mdx
  src/content/certifications/landing-faq.mdx
Labels: content

#2002 repo sync
  src/components/dev-dot-content/mdx-components/mdx-hcp-callout/docs.mdx
  src/components/dev-dot-content/mdx-components/mdx-hcp-callout/index.tsx
  src/content/hcp/docs-landing.json
  src/content/hcp/product-landing.json
  src/content/hcp/tutorials-sidebar.json
  src/data/alert-banner.json
  src/types/products.ts
Labels: automated-reposync-pr

#2016 Updated vault-operations-professional.mdx
  src/content/certifications/exam-faqs/vault-operations-professional.mdx
Labels: content

#2018 fix: remove unauth'd margin bottom
  src/components/mobile-menu-container/mobile-menu-container.module.css
Labels: bug

#2041 fix: don't rewrite waf / onboarding links
  src/views/docs-view/utils/__tests__/rewrite-docs-url.test.ts
  src/views/docs-view/utils/product-url-adjusters.ts
Labels: bug
