Repository hashicorp/dev-portal, pull requests merged in 2023-10, with the labels that each got.

#2191 Some suggested a11y changes for AI integration feature
  src/components/chatbox/chatbox.tsx
  src/components/chatbox/message.tsx
  src/components/command-bar/commands/chat/chat.module.css
  src/components/command-bar/commands/chat/index.tsx
  src/components/command-bar/components/dialog/header.tsx
Labels: proj-gpt-integration, a11y

#2192 [Oct 11] Remove the 'Beta' tag on the side nav
  src/content/hcp/tutorials-sidebar.json
Labels: do not merge

#2196 repo sync - HCP Consul API Docs
  src/pages/hcp/api-docs/consul/[[...page]].tsx
Labels: automated-reposync-pr

#2197 repo sync - Waypoint content updates
  src/content/hcp/tutorials-sidebar.json
  src/content/nomad/product-landing.json
  src/content/waypoint/docs-landing.json
  src/content/waypoint/install-landing.json
  src/content/waypoint/product-landing.json
  src/lib/integrations/fetch-all-integrations.ts
  src/pages/consul/downloads/enterprise.tsx
  src/pages/consul/downloads/index.tsx
  src/pages/vagrant/downloads/index.tsx
  src/pages/waypoint/api-docs/[[...page]].tsx
  src/pages/waypoint/api-docs/api-docs.module.css
  src/pages/waypoint/downloads/downloads.module.css
  src/pages/waypoint/downloads/index.tsx
  src/pages/waypoint/integrations/[organizationSlug]/[integrationSlug]/[integrationVersion]/components/[componentType]/[componentSlug]/index.tsx
  src/pages/waypoint/integrations/[organizationSlug]/[integrationSlug]/[integrationVersion]/index.tsx
  src/pages/waypoint/integrations/[organizationSlug]/[integrationSlug]/index.tsx
  src/pages/waypoint/integrations/[organizationSlug]/[integrationSlug]/integration-readme.module.css
  src/pages/waypoint/integrations/index.tsx
  src/pages/waypoint/integrations/integrations.module.css
  src/views/api-docs-view/index.tsx
  src/views/api-docs-view/types.ts
  src/views/product-downloads-view/boundary/index.tsx
  src/views/product-downloads-view/index.tsx
  src/views/product-downloads-view/types.ts
  src/views/product-integration/component-view/index.tsx
  src/views/product-integration/component-view/server.ts
  src/views/product-integration/readme-view/index.tsx
  src/views/product-integration/readme-view/server.ts
  src/views/product-integrations-landing/index.tsx
  src/views/product-integrations-landing/server.ts
Labels: automated-reposync-pr

#2200 chore: Highlight HashiConf virtual session recordings in banner
  src/data/alert-banner.json
Labels: do not merge

#2203 feat: adds ai feedback button to command bar header
  src/components/chatbox/chatbox.module.css
  src/components/chatbox/chatbox.tsx
  src/components/command-bar/commands/chat/chat.module.css
  src/components/command-bar/commands/chat/index.tsx
  src/components/command-bar/components/dialog/command-bar-dialog.module.css
  src/components/command-bar/components/dialog/header.tsx
  src/components/command-bar/types.ts
  src/constants/ai-feedback-form.ts
Labels: proj-gpt-integration

#2187 feat: better chat error messages
  src/components/chatbox/chatbox.tsx
Labels: stale-exempt, proj-gpt-integration

#2186 Developer AI VQA Cont.
  src/components/chatbox/Markdown.tsx
  src/components/chatbox/chatbox.module.css
  src/components/chatbox/chatbox.tsx
  src/components/chatbox/message.module.css
  src/components/chatbox/message.tsx
  src/components/chatbox/welcome-message.tsx
  src/components/command-bar/commands/chat/chat.module.css
  src/components/command-bar/commands/chat/index.tsx
  src/components/command-bar/components/dialog/command-bar-dialog.module.css
  src/components/command-bar/components/dialog/header.tsx
  src/components/command-bar/types.ts
  src/constants/ai-feedback-form.ts
Labels: proj-gpt-integration

#2205 style: update welcome message width
  src/components/chatbox/chatbox.tsx
  src/components/chatbox/welcome-message.module.css
  src/components/chatbox/welcome-message.tsx
Labels: proj-gpt-integration
