Repository hashicorp/dev-portal, pull requests merged in 2023-04, with the labels that each got.

#1801 chore: fix focus style
  src/components/command-bar/components/activator/command-bar-activator.module.css
Labels: bug, dark-mode

#1793 feat: theme-switcher in user dropdown
  src/components/dropdown-disclosure/components/list-item/index.tsx
  src/components/dropdown-disclosure/components/list-item/types.ts
  src/components/navigation-header/index.tsx
  src/components/theme-switch/index.tsx
  src/components/theme-switcher/index.tsx
  src/components/theme-switcher/theme-switcher.module.css
  src/components/theme-switcher/user-dropdown-switcher/index.tsx
  src/components/theme-switcher/user-dropdown-switcher/user-dropdown-switcher.module.css
  src/components/user-dropdown-disclosure/index.tsx
  src/components/user-dropdown-disclosure/types.ts
  src/lib/auth/user.tsx
  src/styles/themes/types.ts
Labels: dark-mode

#1790 certifications mdx: adds `ThemedImage`
  src/content/certifications/exam-faqs/vault-operations-professional.mdx
  src/views/certifications/components/accordion-with-mdx-content/index.tsx
  src/views/certifications/components/mdx-themed-image/index.tsx
  src/views/certifications/components/mdx-themed-image/mdx-themed-image.module.css
  src/views/certifications/content/utils/collect-md-content-by-heading.ts
Labels: dark-mode

#1792 feat: dark mode toast
  src/layouts/core-dev-dot-layout/index.tsx
  src/lib/toast/make-dark-mode-notification.ts
Labels: dark-mode

#1737 ubuntu: use gpg -o instead of tee for getting gpg key
  src/views/product-downloads-view/helpers.ts
Labels: stale

#1814 refactor: disclosure list item icon placement to right
  src/components/dropdown-disclosure/components/list-item/index.tsx
  src/components/dropdown-disclosure/components/list-item/list-item.module.css
  src/components/mobile-menu-container/components/mobile-user-disclosure/index.tsx
  src/components/mobile-menu-container/components/mobile-user-disclosure/mobile-user-disclosure.module.css
  src/lib/auth/user.tsx
Labels: dark-mode

#1808 feat: theme switcher mobile
  src/components/mobile-menu-container/components/mobile-user-disclosure/index.tsx
  src/components/mobile-menu-container/index.tsx
  src/components/mobile-menu-container/mobile-menu-container.module.css
  src/components/theme-switcher/index.tsx
  src/components/theme-switcher/theme-switcher.module.css
  src/components/theme-switcher/user-dropdown-switcher/index.tsx
  src/components/theme-switcher/user-dropdown-switcher/user-dropdown-switcher.module.css
Labels: dark-mode

#1818 chore: follow up mobile nav
  src/components/mobile-menu-container/components/mobile-user-disclosure/index.tsx
  src/components/mobile-menu-container/index.tsx
Labels: dark-mode

#1822 style: update vault gradient token
  src/styles/themes/dark.css
Labels: dark-mode

#1831 feat(footer): theme switcher with label
  src/components/footer/footer.module.css
  src/components/footer/index.tsx
  src/components/mobile-menu-container/index.tsx
  src/components/mobile-menu-container/mobile-menu-container.module.css
  src/components/theme-switcher/index.tsx
  src/components/theme-switcher/theme-switcher.module.css
  src/components/theme-switcher/user-dropdown-switcher/index.tsx
  src/components/theme-switcher/user-dropdown-switcher/user-dropdown-switcher.module.css
Labels: dark-mode

#1821 chore: removes dark mode flag
  config/base.json
  config/production.json
  config/project-preview.json
  config/tutorials-preview.json
  src/components/user-dropdown-disclosure/index.tsx
  src/layouts/base-new/index.tsx
Labels: dark-mode

#1834 feat: aws themed icon
  src/content/supported-icons.tsx
  src/content/themed-icons/aws-color.tsx
  src/content/themed-icons/img/aws-dark-mode.svg
Labels: dark-mode

#1802 [Assembly] Dark mode
  config/base.json
  config/production.json
  config/project-preview.json
  config/tutorials-preview.json
  src/components/dropdown-disclosure/components/list-item/index.tsx
  src/components/dropdown-disclosure/components/list-item/list-item.module.css
  src/components/dropdown-disclosure/components/list-item/types.ts
  src/components/footer/footer.module.css
  src/components/footer/index.tsx
  src/components/image/image.module.css
  src/components/mobile-menu-container/components/mobile-user-disclosure/index.tsx
  src/components/mobile-menu-container/components/mobile-user-disclosure/mobile-user-disclosure.module.css
  src/components/mobile-menu-container/index.tsx
  src/components/mobile-menu-container/mobile-menu-container.module.css
  src/components/navigation-header/index.tsx
  src/components/theme-switch/index.tsx
  src/components/theme-switcher/index.tsx
  src/components/theme-switcher/theme-switcher.module.css
  src/components/theme-switcher/user-dropdown-switcher/index.tsx
  src/components/theme-switcher/user-dropdown-switcher/user-dropdown-switcher.module.css
  src/components/user-dropdown-disclosure/index.tsx
  src/components/user-dropdown-disclosure/types.ts
  src/content/supported-icons.tsx
  src/content/themed-icons/aws-color.tsx
  src/content/themed-icons/img/aws-dark-mode.svg
  src/layouts/base-new/index.tsx
  src/layouts/core-dev-dot-layout/index.tsx
  src/lib/auth/user.tsx
  src/lib/toast/make-dark-mode-notification.ts
  src/styles/themes/types.ts
Labels: dark-mode

#1833 refactor: non-themed routes to config
  config/base.json
  src/components/footer/index.tsx
  src/components/mobile-menu-container/components/mobile-user-disclosure/index.tsx
  src/components/user-dropdown-disclosure/index.tsx
  src/layouts/core-dev-dot-layout/index.tsx
  src/lib/isThemedPath.ts
Labels: dark-mode

#1758 Making tables with horizontal overflow keyboard operable
  src/components/dev-dot-content/mdx-components/mdx-table/index.tsx
  src/components/dev-dot-content/mdx-components/mdx-table/mdx-table.module.css
  src/lib/get-scroll-data.ts
Labels: do not merge

#1830 Remove Override from Integration Header
  src/components/content-header-card/content-header-card.module.css
  src/components/content-header-card/index.tsx
Labels: stale
