Repository hashicorp/dev-portal, pull requests merged in 2023-05, with the labels that each got.

#1872 support `integration_type`
  analytics/spec/events/integration_library_filter_selected.yaml
  src/components/multi-select/index.tsx
  src/lib/integrations-api-client/integration.ts
  src/views/product-integrations-landing/components/searchable-integrations-list/helpers/analytics.ts
  src/views/product-integrations-landing/components/searchable-integrations-list/index.tsx
  src/views/product-integrations-landing/contexts/integrations-search-context.tsx
Labels: do not merge

#1889 feat: support beta labels in packer api docs
  src/components/accordion-disclosure/index.tsx
  src/components/open-api-page/partials/operation-object/index.tsx
  src/components/open-api-page/partials/operation-object/style.module.css
  src/components/open-api-page/partials/parameter/index.tsx
Labels: stale-exempt

#1914 fix: user dropdown disclosure active bg-color
  src/components/navigation-header/navigation-header.module.css
Labels: bug

#1935 fix: render vertical line when badges exist
  src/components/tutorial-meta/components/badges/index.tsx
Labels: bug
