Repository hashicorp/dev-portal, pull requests merged in 2024-12, with the labels that each got.

#2640 Vault Associate 003 Registration
  src/content/certifications/exam-faqs/vault-associate-002.mdx
  src/content/certifications/exam-faqs/vault-associate-003.mdx
  src/content/certifications/programs/security-automation.json
Labels: stale

#2659 Replace link to CLI tutorial quickstart
  src/content/vault/product-landing.json
Labels: documentation, Tutorials

#2660 Remove Vault CLI quick start tutorials
  src/content/vault/install-landing.json
  src/pages/tutorials/library.tsx
  src/views/docs-view/loaders/__fixtures__/index.mdx
Labels: Tutorials
