Repository hashicorp/dev-portal, pull requests merged in 2024-10, with the labels that each got.

#2574 [Oct 15] Add a tile for Vault Radar on Vault docs home
  src/content/vault/docs-landing.json
Labels: do not merge

#2593 feat: datagrail consent manager
  package-lock.json
  package.json
  src/hooks/use-authentication/index.ts
  src/layouts/base-layout/index.tsx
  src/lib/consent-manager-services/developer.ts
  src/lib/consent-manager-services/io-sites.ts
  src/lib/consent-manager/component.tsx
  src/lib/consent-manager/global.d.ts
  src/lib/consent-manager/index.tsx
  src/lib/consent-manager/types.ts
  src/lib/consent-manager/utils.ts
  src/pages/_document.tsx
Labels: do not merge

#2608 Remove UI colleciton from install page
  src/content/tutorials-landing.json
  src/content/vault/install-landing.json
Labels: documentation, Tutorials

#2614 Remove link to HCP tutorial
  src/content/vault/install-landing.json
Labels: documentation
